### ISSUE TITLE
Pretrained model loading

### ISSUE THREAD

**Issue by 19991105** [xingy038/DS-Depth#3]
Hi! I would like to ask you something. Does the weight loading of the kitti pretrained model also need to be done on the kitti raw data?

**Comment by xingy038** [comment]
It needs test data.

**Comment by 19991105** [comment]
> It needs test data.

I need to refer to the monodepth2 instructions to download the test data, right？

**Comment by xingy038** [comment]
> > It needs test data.
> 
> I need to refer to the monodepth2 instructions to download the test data, right？

Yes

**Comment by 19991105** [comment]
冒昧问一下这个数据文件您还有吗？如果有的话，能发我一下嘛




徐文洁
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xingy038/DS-Depth"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月13日(星期五) 晚上9:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xingy038/DS-Depth] Pretrained model loading (Issue #3)





   
It needs test data.
  
I need to refer to the monodepth2 instructions to download the test data, right？
  
Yes

**Comment by xingy038** [comment]
> 冒昧问一下这个数据文件您还有吗？如果有的话，能发我一下嘛 徐文洁 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xingy038/DS-Depth" ***@***.***&gt;; 发送时间:&nbsp;2024年9月13日(星期五) 晚上9:52 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [xingy038/DS-Depth] Pretrained model loading (Issue #3) It needs test data. I need to refer to the monodepth2 instructions to download the test data, right？ Yes — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你留个邮箱

**Comment by 19991105** [comment]
***@***.***
谢谢大佬




徐文洁
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xingy038/DS-Depth"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月13日(星期五) 晚上9:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xingy038/DS-Depth] Pretrained model loading (Issue #3)





  
冒昧问一下这个数据文件您还有吗？如果有的话，能发我一下嘛 徐文洁 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xingy038/DS-Depth" @.&gt;; 发送时间:&nbsp;2024年9月13日(星期五) 晚上9:52 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [xingy038/DS-Depth] Pretrained model loading (Issue #3) It needs test data. I need to refer to the monodepth2 instructions to download the test data, right？ Yes — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
你留个邮箱

**Comment by xingy038** [comment]
> ***@***.*** 谢谢大佬 徐文洁 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xingy038/DS-Depth" ***@***.***&gt;; 发送时间:&nbsp;2024年9月13日(星期五) 晚上9:59 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [xingy038/DS-Depth] Pretrained model loading (Issue #3) 冒昧问一下这个数据文件您还有吗？如果有的话，能发我一下嘛 徐文洁 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xingy038/DS-Depth" @.&gt;; 发送时间:&nbsp;2024年9月13日(星期五) 晚上9:52 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [xingy038/DS-Depth] Pretrained model loading (Issue #3) It needs test data. I need to refer to the monodepth2 instructions to download the test data, right？ Yes — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 你留个邮箱 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我看不到，你分开写

**Comment by 19991105** [comment]
***@***.****q*.c*o*m
能看到吗
成密文啦


徐文洁
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xingy038/DS-Depth"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月13日(星期五) 晚上10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xingy038/DS-Depth] Pretrained model loading (Issue #3)





  
@.*** 谢谢大佬 徐文洁 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xingy038/DS-Depth" @.&gt;; 发送时间:&nbsp;2024年9月13日(星期五) 晚上9:59 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [xingy038/DS-Depth] Pretrained model loading (Issue #3) 冒昧问一下这个数据文件您还有吗？如果有的话，能发我一下嘛 徐文洁 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xingy038/DS-Depth" @.&gt;; 发送时间:&nbsp;2024年9月13日(星期五) 晚上9:52 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [xingy038/DS-Depth] Pretrained model loading (Issue #3) It needs test data. I need to refer to the monodepth2 instructions to download the test data, right？ Yes — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 你留个邮箱 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
我看不到，你分开写

**Comment by xingy038** [comment]
> ***@***.****q*.c*o*m 能看到吗 成密文啦 徐文洁 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xingy038/DS-Depth" ***@***.***&gt;; 发送时间:&nbsp;2024年9月13日(星期五) 晚上10:08 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [xingy038/DS-Depth] Pretrained model loading (Issue #3) @.*** 谢谢大佬 徐文洁 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xingy038/DS-Depth" @.&gt;; 发送时间:&nbsp;2024年9月13日(星期五) 晚上9:59 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [xingy038/DS-Depth] Pretrained model loading (Issue #3) 冒昧问一下这个数据文件您还有吗？如果有的话，能发我一下嘛 徐文洁 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xingy038/DS-Depth" @.&gt;; 发送时间:&nbsp;2024年9月13日(星期五) 晚上9:52 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [xingy038/DS-Depth] Pretrained model loading (Issue #3) It needs test data. I need to refer to the monodepth2 instructions to download the test data, right？ Yes — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 你留个邮箱 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 我看不到，你分开写 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

成密文了

**Comment by 19991105** [comment]
这样呢？
不好意思麻烦你啦，也有点搞笑哈哈


徐文洁
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xingy038/DS-Depth"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月13日(星期五) 晚上10:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xingy038/DS-Depth] Pretrained model loading (Issue #3)





  
@.q.com 能看到吗 成密文啦 徐文洁 @.** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xingy038/DS-Depth" @.&gt;; 发送时间:&nbsp;2024年9月13日(星期五) 晚上10:08 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [xingy038/DS-Depth] Pretrained model loading (Issue #3) @.*** 谢谢大佬 徐文洁 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xingy038/DS-Depth" @.&gt;; 发送时间:&nbsp;2024年9月13日(星期五) 晚上9:59 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [xingy038/DS-Depth] Pretrained model loading (Issue #3) 冒昧问一下这个数据文件您还有吗？如果有的话，能发我一下嘛 徐文洁 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xingy038/DS-Depth" @.&gt;; 发送时间:&nbsp;2024年9月13日(星期五) 晚上9:52 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [xingy038/DS-Depth] Pretrained model loading (Issue #3) It needs test data. I need to refer to the monodepth2 instructions to download the test data, right？ Yes — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 你留个邮箱 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 我看不到，你分开写 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
成密文了

**Comment by xingy038** [comment]
> 这样呢？ 不好意思麻烦你啦，也有点搞笑哈哈 徐文洁 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xingy038/DS-Depth" ***@***.***&gt;; 发送时间:&nbsp;2024年9月13日(星期五) 晚上10:14 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [xingy038/DS-Depth] Pretrained model loading (Issue #3) @.q.com 能看到吗 成密文啦 徐文洁 @.** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xingy038/DS-Depth" @.&gt;; 发送时间:&nbsp;2024年9月13日(星期五) 晚上10:08 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [xingy038/DS-Depth] Pretrained model loading (Issue #3) @.*** 谢谢大佬 徐文洁 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xingy038/DS-Depth" @.&gt;; 发送时间:&nbsp;2024年9月13日(星期五) 晚上9:59 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [xingy038/DS-Depth] Pretrained model loading (Issue #3) 冒昧问一下这个数据文件您还有吗？如果有的话，能发我一下嘛 徐文洁 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xingy038/DS-Depth" @.&gt;; 发送时间:&nbsp;2024年9月13日(星期五) 晚上9:52 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [xingy038/DS-Depth] Pretrained model loading (Issue #3) It needs test data. I need to refer to the monodepth2 instructions to download the test data, right？ Yes — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 你留个邮箱 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 我看不到，你分开写 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 成密文了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

miaoxy97
163
你给我发个邮件吧。。
